### ISSUE TITLE
Bonded network

### ISSUE THREAD

**Issue by svang-app** [udhos/goben#11]
Hi - One question to you.

I tested this tool on a bonded network (2 ports x 25 Gbps and two such cards) and this gives a combined throughput of 100 Gbps using 4 pots.

But, I do not go beyond these values.

```
2021/04/02 13:27:30 aggregate reading: 19106 Mbps 47789 recv/s
2021/04/02 13:27:30 aggregate writing: 6797 Mbps 16994 send/s
```
The above seems to use only one port.

This is the same case with `iperf` where it does not do load balancing across ports. 

I am using this tool for the first time and it looks very impressive.

Do you know if missed anything obvious?

Thanks

**Comment by udhos** [comment]
There is this known issue with systems that aggregate network interfaces: the algorithm used to distribute frames across the linked interfaces usually does not allow for uniform distribution. Check the documentation of your system to find out if it supports any type of fully uniform load sharing. Some rare systems do support per-packet/per-frame load sharing that produces highly uniform load across linked network interfaces. However most systems don't -- in this case you ought to pick the option that gives the best  load distribution for your case, but it is going to remain far from uniform, some interfaces getting saturated way before others.
