### ISSUE TITLE
how to calculate the bandwidth(speed) from report result，i hope the result is kile 5Gbps

### ISSUE THREAD

**Issue by phygerr** [udhos/goben#15]
i use goben test vm1 to vm2 bandwidth，got result like this

[root@upd-1 ~]# ./goben -udp -hosts 10.0.55.245
2024/01/31 14:00:54 goben version 0.6 runtime go1.18beta1 GOMAXPROCS=8 OS=linux arch=amd64
2024/01/31 14:00:54 connections=1 defaultPort=:8080 listeners=[":8080"] hosts=["10.0.55.245"]
2024/01/31 14:00:54 reportInterval=2s totalDuration=10s
2024/01/31 14:00:54 client mode, udp protocol
2024/01/31 14:00:54 open: opening TLS=true udp 0/1: 10.0.55.245:8080
2024/01/31 14:00:54 handleConnectionClient: starting TCP 0/1 10.0.55.245:8080
2024/01/31 14:00:54 handleConnectionClient: options sent: {2s 10s 1000000 1000000 64000 64000 false 0 map[]}
2024/01/31 14:00:54 clientWriter: starting: 0/1 10.0.55.245:8080
2024/01/31 14:00:54 clientReader: starting: 0/1 10.0.55.245:8080
2024/01/31 14:00:56 0/1  report   clientWriter rate:  23672 Mbps  46235 snd/s
2024/01/31 14:00:56 0/1  report   clientReader rate:     35 Mbps     68 rcv/s
2024/01/31 14:00:58 0/1  report   clientWriter rate:  19150 Mbps  37403 snd/s
2024/01/31 14:00:58 0/1  report   clientReader rate:   3887 Mbps   7592 rcv/s
2024/01/31 14:01:00 0/1  report   clientWriter rate:  18989 Mbps  37088 snd/s
2024/01/31 14:01:00 0/1  report   clientReader rate:   3106 Mbps   6068 rcv/s
2024/01/31 14:01:02 0/1  report   clientWriter rate:  16185 Mbps  31613 snd/s
2024/01/31 14:01:02 0/1  report   clientReader rate:   1480 Mbps   2891 rcv/s
2024/01/31 14:01:04 handleConnectionClient: 10s timer
2024/01/31 14:01:04 workLoop: 0/1 clientReader: read udp 10.0.55.58:43576->10.0.55.245:8080: use of closed network connection
2024/01/31 14:01:04 0/1 average   clientReader rate:   1827 Mbps   3570 rcv/s
2024/01/31 14:01:04 clientReader: exiting: 0/1 10.0.55.245:8080
2024/01/31 14:01:04 workLoop: 0/1 clientWriter: write udp 10.0.55.58:43576->10.0.55.245:8080: use of closed network connection
2024/01/31 14:01:04 0/1 average   clientWriter rate:  19026 Mbps  37161 snd/s
2024/01/31 14:01:04 clientWriter: exiting: 0/1 10.0.55.245:8080
2024/01/31 14:01:04 10.0.55.245:8080 input:
 3888 ┼                     ╭───────╮
 3502 ┤                   ╭─╯       ╰───────────╮
 3117 ┤                 ╭─╯                     ╰───────╮
 2732 ┤              ╭──╯                               ╰────╮
 2347 ┤            ╭─╯                                       ╰────╮
 1961 ┤          ╭─╯                                              ╰─────╮
 1576 ┤       ╭──╯                                                      ╰───
 1191 ┤     ╭─╯
  806 ┤   ╭─╯
  420 ┤╭──╯
   35 ┼╯
         Input Mbps: 10.0.55.245:8080 Connection 0
2024/01/31 14:01:04 10.0.55.245:8080 output:
 23673 ┼╮
 22924 ┤╰───╮
 22175 ┤    ╰───╮
 21427 ┤        ╰──╮
 20678 ┤           ╰───╮
 19929 ┤               ╰───╮
 19181 ┤                   ╰───────────╮
 18432 ┤                               ╰───────────────────╮
 17683 ┤                                                   ╰─────╮
 16935 ┤                                                         ╰─────╮
 16186 ┤                                                               ╰─────
          Output Mbps: 10.0.55.245:8080 Connection 0
2024/01/31 14:01:04 handleConnectionClient: closing: 0/1 10.0.55.245:8080
2024/01/31 14:01:04 aggregate reading: 1827 Mbps 3570 recv/s
2024/01/31 14:01:04 aggregate writing: 19026 Mbps 37161 send/s

can u help me to calculate the udp bandwidth with like  Gbps/s  or  Mbps/s

**Comment by phygerr** [comment]
and can i get the lost package percent from the test result

**Comment by udhos** [comment]
> 2024/01/31 14:01:04 aggregate reading: 1827 Mbps 3570 recv/s
> 2024/01/31 14:01:04 aggregate writing: 19026 Mbps 37161 send/s
> 
> can u help me to calculate the udp bandwidth with like Gbps/s or Mbps/s

The bandwidth is always reported in Mbps (Megabits per second).

Hence your client read 1827 Mbps (1.827 Gbps) on average,
and wrote 19026 Mbps (19.026 Gbps) on average.

> and can i get the lost package percent from the test result

No, it is not, the software does not track statistics about lost packets.

**Comment by phygerr** [comment]
您好，您发来的邮件我已经收到，我将及时对您的邮件做出回复！Hello, I have received your email, I will reply to your email in time.!                                                                 李飞_Phyger

**Comment by phygerr** [comment]
> > 2024/01/31 14:01:04 aggregate reading: 1827 Mbps 3570 recv/s
> > 2024/01/31 14:01:04 aggregate writing: 19026 Mbps 37161 send/s
> > can u help me to calculate the udp bandwidth with like Gbps/s or Mbps/s
> 
> The bandwidth is always reported in Mbps (Megabits per second).
> 
> Hence your client read 1827 Mbps (1.827 Gbps) on average, and wrote 19026 Mbps (19.026 Gbps) on average.
> 
> > and can i get the lost package percent from the test result
> 
> No, you can't, since the software does not track statistics about lost packets.


### 
tks for your reply, first question is my fault, and tks your project again.

i want get some advice  on how to test the maximum bandwidth method from you, now i try to get the max bandwidth by use different cpu process  num, i think maybe we can define the fixed bandwith to do the perform test.
Put it another way, if use goben to test and git a result, how can i confirm  it is the best bandwidth?

Looking forward to your answer, tks very.

**Comment by phygerr** [comment]
>> and can i get the lost package percent from the test result
> No, you can't, since the software does not track statistics about lost packets.

oh, i remember now, Is it possible to compare with clientReader and clientWrite to confirm the max bandwidth，because i find when clientReader  equal clientWrite the lost package is 0%，most question expose on udp protocol，tcp protocol is reliable.

**Comment by udhos** [comment]
@phygerr I would try different things in order to find the highest possible rate, like:

1 - start with a single tcp connection 
2 - increase the number of tcp connections gradually until the rate starts to drop
3 - now you should have an idea of the max possible rate you could attempt to increase by using udp with rate limit 

You can also attempt to tweak buffer sites.

Something like that.

**Comment by phygerr** [comment]
您好，您发来的邮件我已经收到，我将及时对您的邮件做出回复！Hello, I have received your email, I will reply to your email in time.!                                                                 李飞_Phyger
