### ISSUE TITLE
does this tool support concurrent connections from multiple devices?

### ISSUE THREAD

**Issue by wmclendon** [udhos/goben#6]
Hello,

this tool looks very interesting, but I am curious, and my apologies if this seems a dumb question -- does it support concurrent connections from multiple clients?  i.e. if I have client A in an office and client B in another office, and they both try to hit the server at the same time, will it service both simultaneously?

My use case is around having a powerful server say in central DC and client in various locations around enterprise that can use it as test point for simple bandwidth testing of the site, but its possible I would have many clients connecting at once.

Thanks.

**Comment by wmclendon** [comment]
apologies, I seemed to have passed straight over the line in the documentation where you indicate 'Spawns multiple concurrent lightweight goroutines to handle multiple parallel traffic streams.'

I guess, does that mean multiple clients, or single client connecting on multiple connections similar to iperf's parallel option (or perhaps they are treated one in the same).

thanks.

**Comment by udhos** [comment]
> I guess, does that mean multiple clients, or single client connecting on multiple connections similar to iperf's parallel option (or perhaps they are treated one in the same).

Yes, it can do both cases concurrently.

For instance, run server on host A (address 1.1.1.1):
`host-A$ goben`

Now run client on host B opening 2 connections against the server:
`host-B$ goben -hosts 1.1.1.1 -connections 2`

Now run client on host C opening 3 connections against the server:
 `host-C$ goben -hosts 1.1.1.1 -connections 3`

You can run clients on hosts B and C against one single server on host A.

For testing, you can also run everything on a single machine by setting '-hosts localhost' in every client:

```
host-A$ goben
host-A$ goben -hosts localhost -connections 2
host-A$ goben -hosts localhost -connections 3
```

Of course, each goben invokation should be on a dedicated window/session/terminal/console.

**Comment by wmclendon** [comment]
awsome thank you for the quick response.  This looks very useful I hope to try it out here soon!
