### ISSUE TITLE
How to test between two IPv6 addresses?

### ISSUE THREAD

**Issue by gdluca** [udhos/goben#8]
Hi,
is IPv6 supported? Tried with "goben --hosts 2001:db8::beef" but have the following error:

dial tcp: 2001db8::beef: dial tcp: address 2001db8::beef: too many colons in address

Anyway, thanks for this useful tool.

**Comment by udhos** [comment]
Hi,
Yes, IPv6 is supported.
However Go parsing libraries expect square brackets around IPv6 addresses.
Try like this:
`goben --hosts [2001:db8::beef]`
Have fun!

**Comment by gdluca** [comment]
Thank you!
